trigger:
- main

pr:
- main

jobs:
- job: BuildAndDeploy
  displayName: Build and Deploy Docker Image
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Checkout@2
    inputs:
      repository: self

  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      containerRegistry: 'dockerhub'
      repository: 'nginx'
      tags: |
        $(Build.BuildId)
      Dockerfile: '**/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      arguments: '--build-arg BUILDKIT_INLINE_CACHE=1'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'my-azure-subscription'
      appName: 'my-web-app'
      package: '$(Build.ArtifactStagingDirectory)/nginx:$(Build.BuildId)'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'my-azure-subscription'
      scriptType: 'bash'
      scriptPath: 'deploy.sh'
      arguments: '--image nginx:$(Build.BuildId)'
